### PR TITLE
Fix UInt128

### LINKED ISSUE #62: Bug: UInt128 incorrect decoding
##### Description:
When trying to decode "perfectly sized" (i.e 16 bytes) SCALE encoded byte array into `UInt128`, it fails to decode it correctly. In particular, when the leading byte is 0, `UInt128` always decodes the value into 0.

- Example:

Array of bytes: `[0, 2, 3, 0, 0, 0, 0, 0, 3, 2, 5, 0, 0, 0, 0, 0]` is decoded into 0
while the correct value should be: `10445440945880610485074064037642240`

### PR DESCRIPTION
**Pull request by dastanbeksamatov**
### Fix UInt128
 
Fixes #62 

- Refactor decoding and encoding for UInt128
- Refactor tests for changes

### CODE REVIEW

File: assembly/utils/Arrays.ts [hunk 1]
```diff
@@ -19,4 +19,16 @@ export namespace ArrayUtils {
         }
         return true;
     }
+
+    /**
+     * Returns new Array<u8> from Uint8 Typed array
+     * @param typedArr 
+     */
+    export function toU8Array(typedArr: Uint8Array): u8[] {
+        let res = new Array<u8>(2);
```
Comment (Daniel-K-Ivanov) [inline assembly/utils/Arrays.ts]: why are you creating this array with capacity 2? What if `typedArr` has length > than 2?

**Review by Daniel-K-Ivanov — CHANGES_REQUESTED** [review]

**Review by Daniel-K-Ivanov — APPROVED** [review]
